apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-web-v1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web

  template:
    metadata:
      name: node-web
      labels:
        app: node-web

    spec:
      containers:
      - image: whatwant/node-web:1.0
        name: node-web
        ports:
        - containerPort: 8080
          protocol: TCP

