apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: hostpath

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu

  template:
    metadata:
      labels:
        app: ubuntu

    spec:
      containers:
      - image: ubuntu:20.04
        name: worker
        command: ["/bin/sleep", "3650d"]
        volumeMounts:
        - name: hostpath-demo
          mountPath: /data/hostpath

      volumes:
      - name: hostpath-demo
        hostPath:
          path: /tmp/hostpath-demo
          type: DirectoryOrCreate
