apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    release: stable
    env: staging

spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain

  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/tmp/data"
    type: DirectoryOrCreate
