apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    k8s-app: node-exporter

spec:
  selector:
    matchLabels:
      k8s-app: node-exporter

  template:
    metadata:
      labels:
        k8s-app: node-exporter

    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter

        ports:
        - containerPort: 9100
          protocol: TCP
          name: http
