apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: kube-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kube-state-metrics

  template:
    metadata:
      labels:
        app: kube-state-metrics

    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v1.8.0
        name: kube-state-metrics

        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry

## LivenessProbe
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5

## ReadinessProbe
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5

## nodeSelector
      nodeSelector:
        kubernetes.io/os: linux

## ServiceAccount
      serviceAccountName: kube-state-metrics
