apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
    group: mongodb

spec:
  type: NodePort

  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 30270

  selector:
    app: mongodb
