apiVersion: v1
kind: Pod
metadata:
  name: private-nginx
  labels:
    app: simple

spec:
  serviceAccountName: my-service-account
  containers:
  - name: simple
    image: whatwant/simple-nginx:v0.1
    imagePullPolicy: Always
