apiVersion: v1
kind: Pod
metadata:
  name: git-sync
  labels:
    app: git-sync

spec:
  volumes:
  - name: git-secret
    secret:
      secretName: git-creds
      defaultMode: 0400

  containers:
  - name: git-sync
    image: k8s.gcr.io/git-sync:v3.1.5

    args:
     - "--ssh"
     - "--repo=git@github.com:whatwant-school/private-repo"
     - "--dest=private-repo"
     - "--branch=main"
     - "--depth=1"

    securityContext:
      runAsUser: 65533 # git-sync user

    volumeMounts:
    - name: git-secret
      mountPath: /etc/git-secret
      readOnly: true

  securityContext:
    fsGroup: 65533 # to make SSH key readable
