apiVersion: v1
kind: Pod
metadata:
  name: ambassador

spec:
  containers:
  - name: curl
    image: tutum/curl
    command: ["/bin/sleep", "3650d"]

  - name: ambassador
    image: luksa/kubectl-proxy:latest
